name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - run: "brew info libansilove $(brew deps libansilove) --json | jq '[.[] | {name, version: .versions.stable}]' > Brewfile.lock.json"
        if: ${{ matrix.os == 'macos-latest' }}
        env:
          HOMEBREW_NO_ENV_HINTS: 1
      - uses: actions/cache@v4
        if: ${{ matrix.os == 'macos-latest' }}
        with:
          path: ~/Library/Caches/Homebrew
          key: ${{ runner.os }}-homebrew-${{ hashFiles('Brewfile.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-homebrew-${{ hashFiles('Brewfile.lock.json') }}
            ${{ runner.os }}-homebrew-
      - run: brew install libansilove
        if: ${{ matrix.os == 'macos-latest' }}
      - run: |
          sudo apt update
          sudo apt install libansilove-dev
        if: ${{ matrix.os == 'ubuntu-latest' }}
      - uses: shivammathur/setup-php@v2
        with:
          tools: pie
      - name: Build
        run: |
          phpize
          ./configure
          make
      - name: Test
        run: make test
      - uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          path: php_test_results_*.txt
      - run: pie install --ansi
      - run: php --re ansilove
